src/Entity/Stagiaire.php
<?php

namespace App\Entity;

use App\Repository\StagiaireRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: StagiaireRepository::class)]
class Stagiaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateNaissance = null;

    #[ORM\Column(length: 50)]
    private ?string $sex = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse = null;

    #[ORM\Column(length: 255)]
    private ?string $ville = null;

    #[ORM\Column(length: 20)]
    private ?string $cp = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $photo = null;

    #[ORM\ManyToMany(targetEntity: Session::class, mappedBy: 'stagiaires')]
    private Collection $sessions;

    public function __construct()
    {
        $this->sessions = new ArrayCollection();
    }

   

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->dateNaissance;
    }

    public function setDateNaissance(\DateTimeInterface $dateNaissance): self
    {
        $this->dateNaissance = $dateNaissance;

        return $this;
    }

    public function getSex(): ?string
    {
        return $this->sex;
    }

    public function setSex(string $sex): self
    {
        $this->sex = $sex;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(string $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getAge(){
        $now = new \DateTime();
        $interval = date_diff($this->dateNaissance, $now);
        return $interval->format("%Y");
    }

    /**
     * @return Collection<int, Session>
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): self
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions->add($session);
            $session->addStagiaire($this);
        }

        return $this;
    }

    public function removeSession(Session $session): self
    {
        if ($this->sessions->removeElement($session)) {
            $session->removeStagiaire($this);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->prenom. " " .$this->nom;
    }

    
}

src/Form/StagiaireType.php
<?php

namespace App\Form;

use App\Entity\Session;
use App\Entity\Stagiaire;
use App\Form\SessionType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class StagiaireType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('prenom',TextType::class,['attr'=>['class'=>'form-control']])
            ->add('nom',TextType::class,['attr'=>['class'=>'form-control']])
            ->add('dateNaissance',DateType::class,['widget' =>'single_text'])
            ->add('sex',TextType::class,['attr'=>['class'=>'form-control']])
            ->add('adresse',TextType::class,['attr'=>['class'=>'form-control']])
            ->add('ville',TextType::class,['attr'=>['class'=>'form-control']])
            ->add('cp',TextType::class,['attr'=>['class'=>'form-control']])
            ->add('email',TextType::class,['attr'=>['class'=>'form-control']])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Stagiaire::class,
        ]);
    }
}

src/Controller/StagiaireController.php
<?php

namespace App\Controller;

use App\Entity\Stagiaire;
use App\Form\StagiaireType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class StagiaireController extends AbstractController
{
    #[Route('/stagiaire', name: 'app_stagiaire')]
    public function index(EntityManagerInterface  $entityManager): Response
    {
        $stagiaires = $entityManager->getRepository(Stagiaire::class)->findAll();
        return $this->render('stagiaire/index.html.twig', [
                'stagiaires' => $stagiaires,
            ]);
    }

    #[Route('/stagiaire/add', name: 'add_stagiaire')]
    #[Route('/stagiaire/{id}/edit', name: 'edit_stagiaire')]
    public function add(EntityManagerInterface $entityManager, Stagiaire $stagiaire = null, Request $request): Response 
    {
        if (!$stagiaire){
            $stagiaire = new stagiaire();
        }
        // on crée le formulaire 
        $form = $this->createForm(StagiaireType::class, $stagiaire);
        $form->handleRequest($request);

        //quand on sousmet le formulaire 
        if($form->isSubmitted() && $form->isValid()){

            $stagiaire = $form->getData();
            $entityManager->persist($stagiaire);// = prepare
            $entityManager->flush();// execute, on envoie les données dans la db 

            return $this->redirectToRoute('app_stagiaire');

        }

        // vue pour afficher le formulaire 
        return $this->render('stagiaire/addStagiaire.html.twig', [
           'formAddstagiaire' => $form->createView(),
           'edit'=> $stagiaire->getId()
            
        ]);

    }

    #[Route('/stagiaire/{id}/delete', name: 'delete_stagiaire')]
    public function delete(EntityManagerInterface $entityManager, Stagiaire $stagiaire): Response
    {
        $entityManager->remove($stagiaire);
        $entityManager->flush();

        return $this->redirectToRoute('app_session');

    }

    
    
    #[Route('/stagiaire/{id}', name: 'show_stagiaire')]
    public function show(Stagiaire $stagiaire): Response
    {
        return $this->render('stagiaire/detailStagiaire.html.twig', [
            'stagiaire' => $stagiaire,
        ]);
    }
}

templates/stagiaire/addStagiaire.html.twig
{% extends 'base.html.twig' %}

{% block title %}AddStagiaire{% endblock %}

{% block body %}
{% if edit %}
    <h1>Edit un stagiaire</h1>
{% else %}
    <h1> ajouter un stagiaire</h1>
{% endif %}

{# {{form(formAddstagiaire)}} #}

{{ form_start(formAddstagiaire) }}

    <div class="nomPrenom">
        {{ form_row(formAddstagiaire.prenom) }}
        {{ form_row(formAddstagiaire.nom) }}
    </div>
    <div>
        {{ form_row(formAddstagiaire.dateNaissance) }}
        {{ form_row(formAddstagiaire.sex) }}
        {{ form_row(formAddstagiaire.adresse) }}
        {{ form_row(formAddstagiaire.ville) }}
        {{ form_row(formAddstagiaire.cp) }}
        {{ form_row(formAddstagiaire.email) }}
        {{ form_row(formAddstagiaire.photo) }}
        {{ form_row(formAddstagiaire.submit) }}
    </div>

{{ form_end(formAddstagiaire) }}


{% endblock %}

templates/stagiaire/detailStagiaire.html.twig
{% extends 'base.html.twig' %}

{% block title %}DetailSession{% endblock %}

{% block body %}
<div class="constainerSta">
    <div class="card p-3 bg-light" style="display: flex; flex-direction: column; align-items: center; width: 25rem;">
        <h1> {{ stagiaire }}</h1>
        <p>
            Date de Naissances: {{stagiaire.dateNaissance | date ('d/m/Y') }}, {{stagiaire.age}} ans. <br>
            Adresse: {{stagiaire.adresse}} <br>
            Cp: {{stagiaire.cp}} <br>
            Ville: {{stagiaire.ville}} <br>
            Courriel: {{stagiaire.email}} <br>
        </p>
    
        <div class="card-body">
            <h3>Sessions prevues</h3>
            {% for session in stagiaire.sessions %}
            <li>
                <a href="{{ path('show_session', {'id': session.id})}}">{{ session }}</a> du {{session.dateDebut| date ('d/m/Y')}} au {{session.dateFin| date ('d/m/Y')}}
            </li>
            {% endfor %}
        </div>
    </div>
</div>



{% endblock %}

templates/stagiaire/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello StagiaireController!{% endblock %}

{% block body %}

    <h1>Listes des stagiaires</h1>

    <a class="btn btn-primary" href="{{ path('add_stagiaire')}}">Add stagiaire </a><br>

    {% for stagiaire in stagiaires %}

        <a href="{{ path('show_stagiaire', {'id': stagiaire.id})}}">{{stagiaire}}</a>
        <a class="btn btn-warning" href="{{ path('edit_stagiaire', {'id':stagiaire.id}) }}">Edit</a> 
        <a class="btn btn-danger" href="{{ path('delete_stagiaire', {'id':stagiaire.id}) }}">Delete</a><br>

    {% endfor %}

{% endblock %}